### ISSUE TITLE
one or two binders?

### ISSUE THREAD

**Issue by mhweber** [mhweber/AWRA2022GeoWorkshop#4]
Can we use https://mybinder.org/v2/gh/cheginit/AWRA2022GeoWorkshop/HEAD for the jupyter notebook I just added to notebooks folder or should I create another binder and badge for this one?

**Comment by cheginit** [comment]
Yes, the whole workshop folder will be there. So there's no need to create additional badges. Binder automatically adds the modified/new files to the Jupyter notebook instance that it creates.

**Comment by cheginit** [comment]
You just need to make sure to include all the R/Python dependencies in the `environment.yml` file. Once we finalize all the notebooks and determined all the dependencies, we need to structure the files nicely with appropriate names and update the env file to based on the dependencies and we'll test the binder to make sure things work as intended. For now, we don't have to worry about the binder.

**Comment by mhweber** [comment]
Sounds good
